import type { GlobalPlaceCandidate } from '../../application/e2e/global-place-selector.port';

// Derived from GeoNames cities5000, countryInfo and admin1CodesASCII extracts.
// GeoNames data is licensed under CC BY 4.0: https://www.geonames.org/
export const GLOBAL_PLACE_CATALOG: readonly GlobalPlaceCandidate[] = [
  {"placeName": "Algiers", "country": "Algeria", "region": "Algiers", "continent": "Africa"},
  {"placeName": "Luanda", "country": "Angola", "region": "Luanda", "continent": "Africa"},
  {"placeName": "Cotonou", "country": "Benin", "region": "Littoral", "continent": "Africa"},
  {"placeName": "Gaborone", "country": "Botswana", "region": "Gaborone", "continent": "Africa"},
  {"placeName": "Ouagadougou", "country": "Burkina Faso", "region": "Centre", "continent": "Africa"},
  {"placeName": "Bujumbura", "country": "Burundi", "region": "Bujumbura Mairie", "continent": "Africa"},
  {"placeName": "Praia", "country": "Cabo Verde", "region": "Praia", "continent": "Africa"},
  {"placeName": "Douala", "country": "Cameroon", "region": "Littoral", "continent": "Africa"},
  {"placeName": "Bangui", "country": "Central African Republic", "region": "Bangui", "continent": "Africa"},
  {"placeName": "N'Djamena", "country": "Chad", "region": "N’Djaména", "continent": "Africa"},
  {"placeName": "Moroni", "country": "Comoros", "region": "Grande Comore", "continent": "Africa"},
  {"placeName": "Kinshasa", "country": "Democratic Republic of the Congo", "region": "Kinshasa", "continent": "Africa"},
  {"placeName": "Djibouti", "country": "Djibouti", "region": "Djibouti", "continent": "Africa"},
  {"placeName": "Cairo", "country": "Egypt", "region": "Cairo", "continent": "Africa"},
  {"placeName": "Bata", "country": "Equatorial Guinea", "region": "Litoral", "continent": "Africa"},
  {"placeName": "Asmara", "country": "Eritrea", "region": "Maekel", "continent": "Africa"},
  {"placeName": "Manzini", "country": "Eswatini", "region": "Manzini Region", "continent": "Africa"},
  {"placeName": "Addis Ababa", "country": "Ethiopia", "region": "Addis Ababa", "continent": "Africa"},
  {"placeName": "Libreville", "country": "Gabon", "region": "Estuaire", "continent": "Africa"},
  {"placeName": "Serekunda", "country": "Gambia", "region": "Banjul", "continent": "Africa"},
  {"placeName": "Kumasi", "country": "Ghana", "region": "Ashanti", "continent": "Africa"},
  {"placeName": "Conakry", "country": "Guinea", "region": "Conakry", "continent": "Africa"},
  {"placeName": "Bissau", "country": "Guinea-Bissau", "region": "Bissau", "continent": "Africa"},
  {"placeName": "Abidjan", "country": "Ivory Coast", "region": "Abidjan Autonomous District", "continent": "Africa"},
  {"placeName": "Nairobi", "country": "Kenya", "region": "Nairobi County", "continent": "Africa"},
  {"placeName": "Maseru", "country": "Lesotho", "region": "Maseru District", "continent": "Africa"},
  {"placeName": "Monrovia", "country": "Liberia", "region": "Montserrado County", "continent": "Africa"},
  {"placeName": "Tripoli", "country": "Libya", "region": "Tripoli", "continent": "Africa"},
  {"placeName": "Antananarivo", "country": "Madagascar", "region": "Analamanga", "continent": "Africa"},
  {"placeName": "Lilongwe", "country": "Malawi", "region": "Central Region", "continent": "Africa"},
  {"placeName": "Bamako", "country": "Mali", "region": "Bamako", "continent": "Africa"},
  {"placeName": "Nouakchott", "country": "Mauritania", "region": null, "continent": "Africa"},
  {"placeName": "Port Louis", "country": "Mauritius", "region": "Port Louis", "continent": "Africa"},
  {"placeName": "Mamoudzou", "country": "Mayotte", "region": "Mamoudzou", "continent": "Africa"},
  {"placeName": "Casablanca", "country": "Morocco", "region": "Casablanca-Settat", "continent": "Africa"},
  {"placeName": "Maputo", "country": "Mozambique", "region": "Maputo City", "continent": "Africa"},
  {"placeName": "Windhoek", "country": "Namibia", "region": "Khomas Region", "continent": "Africa"},
  {"placeName": "Niamey", "country": "Niger", "region": "Niamey", "continent": "Africa"},
  {"placeName": "Lagos", "country": "Nigeria", "region": "Lagos", "continent": "Africa"},
  {"placeName": "Brazzaville", "country": "Republic of the Congo", "region": "Brazzaville", "continent": "Africa"},
  {"placeName": "Saint-Denis", "country": "Reunion", "region": "Reunion", "continent": "Africa"},
  {"placeName": "Kigali", "country": "Rwanda", "region": "Kigali", "continent": "Africa"},
  {"placeName": "Georgetown", "country": "Saint Helena", "region": "Ascension", "continent": "Africa"},
  {"placeName": "São Tomé", "country": "Sao Tome and Principe", "region": "São Tomé Island", "continent": "Africa"},
  {"placeName": "Dakar", "country": "Senegal", "region": "Dakar", "continent": "Africa"},
  {"placeName": "Victoria", "country": "Seychelles", "region": "La Rivière Anglaise", "continent": "Africa"},
  {"placeName": "Freetown", "country": "Sierra Leone", "region": "Western Area", "continent": "Africa"},
  {"placeName": "Mogadishu", "country": "Somalia", "region": "Banaadir", "continent": "Africa"},
  {"placeName": "Johannesburg", "country": "South Africa", "region": "Gauteng", "continent": "Africa"},
  {"placeName": "Juba", "country": "South Sudan", "region": "Central Equatoria", "continent": "Africa"},
  {"placeName": "Khartoum", "country": "Sudan", "region": "Khartoum", "continent": "Africa"},
  {"placeName": "Dar es Salaam", "country": "Tanzania", "region": "Dar es Salaam Region", "continent": "Africa"},
  {"placeName": "Lomé", "country": "Togo", "region": "Maritime", "continent": "Africa"},
  {"placeName": "Tunis", "country": "Tunisia", "region": "Tunis Governorate", "continent": "Africa"},
  {"placeName": "Kampala", "country": "Uganda", "region": "Central Region", "continent": "Africa"},
  {"placeName": "Laayoune", "country": "Western Sahara", "region": null, "continent": "Africa"},
  {"placeName": "Lusaka", "country": "Zambia", "region": "Lusaka Province", "continent": "Africa"},
  {"placeName": "Harare", "country": "Zimbabwe", "region": "Harare", "continent": "Africa"},
  {"placeName": "Kabul", "country": "Afghanistan", "region": "Kabul", "continent": "Asia"},
  {"placeName": "Yerevan", "country": "Armenia", "region": "Yerevan", "continent": "Asia"},
  {"placeName": "Baku", "country": "Azerbaijan", "region": "Baki", "continent": "Asia"},
  {"placeName": "Al Muharraq", "country": "Bahrain", "region": "Muharraq", "continent": "Asia"},
  {"placeName": "Dhaka", "country": "Bangladesh", "region": "Dhaka Division", "continent": "Asia"},
  {"placeName": "Thimphu", "country": "Bhutan", "region": "Thimphu District", "continent": "Asia"},
  {"placeName": "Bandar Seri Begawan", "country": "Brunei", "region": "Brunei-Muara District", "continent": "Asia"},
  {"placeName": "Phnom Penh", "country": "Cambodia", "region": "Phnom Penh", "continent": "Asia"},
  {"placeName": "Shanghai", "country": "China", "region": "Shanghai", "continent": "Asia"},
  {"placeName": "West Island", "country": "Cocos Islands", "region": null, "continent": "Asia"},
  {"placeName": "Tbilisi", "country": "Georgia", "region": "Tbilisi", "continent": "Asia"},
  {"placeName": "Hong Kong", "country": "Hong Kong", "region": null, "continent": "Asia"},
  {"placeName": "Mumbai", "country": "India", "region": "Maharashtra", "continent": "Asia"},
  {"placeName": "Jakarta", "country": "Indonesia", "region": "Jakarta", "continent": "Asia"},
  {"placeName": "Tehran", "country": "Iran", "region": "Tehran", "continent": "Asia"},
  {"placeName": "Baghdad", "country": "Iraq", "region": "Baghdad", "continent": "Asia"},
  {"placeName": "Jerusalem", "country": "Israel", "region": "Jerusalem", "continent": "Asia"},
  {"placeName": "Tokyo", "country": "Japan", "region": "Tokyo", "continent": "Asia"},
  {"placeName": "Amman", "country": "Jordan", "region": "Amman", "continent": "Asia"},
  {"placeName": "Almaty", "country": "Kazakhstan", "region": "Almaty", "continent": "Asia"},
  {"placeName": "Al Aḩmadī", "country": "Kuwait", "region": "Al Aḩmadī", "continent": "Asia"},
  {"placeName": "Bishkek", "country": "Kyrgyzstan", "region": "Bishkek", "continent": "Asia"},
  {"placeName": "Vientiane", "country": "Laos", "region": "Vientiane Prefecture", "continent": "Asia"},
  {"placeName": "Beirut", "country": "Lebanon", "region": "Beirut", "continent": "Asia"},
  {"placeName": "Macau", "country": "Macao", "region": null, "continent": "Asia"},
  {"placeName": "Kuala Lumpur", "country": "Malaysia", "region": "Kuala Lumpur", "continent": "Asia"},
  {"placeName": "Male", "country": "Maldives", "region": "Kaafu Atoll", "continent": "Asia"},
  {"placeName": "Ulan Bator", "country": "Mongolia", "region": "Ulaanbaatar", "continent": "Asia"},
  {"placeName": "Yangon", "country": "Myanmar", "region": "Yangon", "continent": "Asia"},
  {"placeName": "Kathmandu", "country": "Nepal", "region": "Bagmati Province", "continent": "Asia"},
  {"placeName": "Pyongyang", "country": "North Korea", "region": "Pyongyang", "continent": "Asia"},
  {"placeName": "Muscat", "country": "Oman", "region": "Muscat", "continent": "Asia"},
  {"placeName": "Lahore", "country": "Pakistan", "region": "Punjab", "continent": "Asia"},
  {"placeName": "East Jerusalem", "country": "Palestinian Territory", "region": "West Bank", "continent": "Asia"},
  {"placeName": "Quezon City", "country": "Philippines", "region": "National Capital Region", "continent": "Asia"},
  {"placeName": "Doha", "country": "Qatar", "region": "Baladiyat ad Dawhah", "continent": "Asia"},
  {"placeName": "Jeddah", "country": "Saudi Arabia", "region": "Mecca Region", "continent": "Asia"},
  {"placeName": "Singapore", "country": "Singapore", "region": null, "continent": "Asia"},
  {"placeName": "Seoul", "country": "South Korea", "region": "Seoul", "continent": "Asia"},
  {"placeName": "Colombo", "country": "Sri Lanka", "region": "Western Province", "continent": "Asia"},
  {"placeName": "Aleppo", "country": "Syria", "region": "Aleppo", "continent": "Asia"},
  {"placeName": "Taipei", "country": "Taiwan", "region": "Taiwan", "continent": "Asia"},
  {"placeName": "Dushanbe", "country": "Tajikistan", "region": "Dushanbe", "continent": "Asia"},
  {"placeName": "Bangkok", "country": "Thailand", "region": "Bangkok", "continent": "Asia"},
  {"placeName": "Istanbul", "country": "Turkey", "region": "Istanbul", "continent": "Asia"},
  {"placeName": "Ashgabat", "country": "Turkmenistan", "region": "Ashgabat", "continent": "Asia"},
  {"placeName": "Dubai", "country": "United Arab Emirates", "region": "Dubai", "continent": "Asia"},
  {"placeName": "Tashkent", "country": "Uzbekistan", "region": "Tashkent", "continent": "Asia"},
  {"placeName": "Ho Chi Minh City", "country": "Vietnam", "region": "Ho Chi Minh City (HCMC)", "continent": "Asia"},
  {"placeName": "Sanaa", "country": "Yemen", "region": "Amanat Alasimah", "continent": "Asia"},
  {"placeName": "Mariehamn", "country": "Aland Islands", "region": "Mariehamn", "continent": "Europe"},
  {"placeName": "Tirana", "country": "Albania", "region": "Tirana", "continent": "Europe"},
  {"placeName": "Andorra la Vella", "country": "Andorra", "region": "Andorra la Vella", "continent": "Europe"},
  {"placeName": "Vienna", "country": "Austria", "region": "Vienna", "continent": "Europe"},
  {"placeName": "Minsk", "country": "Belarus", "region": "Minsk City", "continent": "Europe"},
  {"placeName": "Brussels", "country": "Belgium", "region": "Brussels Capital", "continent": "Europe"},
  {"placeName": "Sarajevo", "country": "Bosnia and Herzegovina", "region": "Federation of B&H", "continent": "Europe"},
  {"placeName": "Sofia", "country": "Bulgaria", "region": "Sofia-Capital", "continent": "Europe"},
  {"placeName": "Zagreb", "country": "Croatia", "region": "Zagreb", "continent": "Europe"},
  {"placeName": "Nicosia", "country": "Cyprus", "region": "Nicosia", "continent": "Europe"},
  {"placeName": "Prague", "country": "Czechia", "region": "Prague", "continent": "Europe"},
  {"placeName": "Copenhagen", "country": "Denmark", "region": "Capital Region", "continent": "Europe"},
  {"placeName": "Tallinn", "country": "Estonia", "region": "Harjumaa", "continent": "Europe"},
  {"placeName": "Tórshavn", "country": "Faroe Islands", "region": "Streymoy", "continent": "Europe"},
  {"placeName": "Helsinki", "country": "Finland", "region": "Uusimaa", "continent": "Europe"},
  {"placeName": "Paris", "country": "France", "region": "Île-de-France", "continent": "Europe"},
  {"placeName": "Berlin", "country": "Germany", "region": "State of Berlin", "continent": "Europe"},
  {"placeName": "Gibraltar", "country": "Gibraltar", "region": null, "continent": "Europe"},
  {"placeName": "Athens", "country": "Greece", "region": "Attica", "continent": "Europe"},
  {"placeName": "Saint Peter Port", "country": "Guernsey", "region": "St Peter Port", "continent": "Europe"},
  {"placeName": "Budapest", "country": "Hungary", "region": "Budapest", "continent": "Europe"},
  {"placeName": "Reykjavík", "country": "Iceland", "region": "Capital Region", "continent": "Europe"},
  {"placeName": "Dublin", "country": "Ireland", "region": "Leinster", "continent": "Europe"},
  {"placeName": "Douglas", "country": "Isle of Man", "region": "Douglas", "continent": "Europe"},
  {"placeName": "Rome", "country": "Italy", "region": "Lazio", "continent": "Europe"},
  {"placeName": "Saint Helier", "country": "Jersey", "region": "St Helier", "continent": "Europe"},
  {"placeName": "Pristina", "country": "Kosovo", "region": "Pristina", "continent": "Europe"},
  {"placeName": "Riga", "country": "Latvia", "region": "Riga", "continent": "Europe"},
  {"placeName": "Schaan", "country": "Liechtenstein", "region": "Schaan", "continent": "Europe"},
  {"placeName": "Vilnius", "country": "Lithuania", "region": "Vilnius", "continent": "Europe"},
  {"placeName": "Luxembourg", "country": "Luxembourg", "region": "Luxembourg", "continent": "Europe"},
  {"placeName": "San Pawl il-Baħar", "country": "Malta", "region": "Saint Paul’s Bay", "continent": "Europe"},
  {"placeName": "Chisinau", "country": "Moldova", "region": "Chișinău Municipality", "continent": "Europe"},
  {"placeName": "Monaco", "country": "Monaco", "region": "Municipality of Monaco", "continent": "Europe"},
  {"placeName": "Podgorica", "country": "Montenegro", "region": "Podgorica", "continent": "Europe"},
  {"placeName": "Skopje", "country": "North Macedonia", "region": "Grad Skopje", "continent": "Europe"},
  {"placeName": "Oslo", "country": "Norway", "region": "Oslo", "continent": "Europe"},
  {"placeName": "Warsaw", "country": "Poland", "region": "Mazovia", "continent": "Europe"},
  {"placeName": "Lisbon", "country": "Portugal", "region": "Lisbon", "continent": "Europe"},
  {"placeName": "Bucharest", "country": "Romania", "region": "Bucharest", "continent": "Europe"},
  {"placeName": "Moscow", "country": "Russia", "region": "Moscow", "continent": "Europe"},
  {"placeName": "Serravalle", "country": "San Marino", "region": "Serravalle", "continent": "Europe"},
  {"placeName": "Belgrade", "country": "Serbia", "region": "Central Serbia", "continent": "Europe"},
  {"placeName": "Bratislava", "country": "Slovakia", "region": "Bratislava Region", "continent": "Europe"},
  {"placeName": "Ljubljana", "country": "Slovenia", "region": "Ljubljana", "continent": "Europe"},
  {"placeName": "Madrid", "country": "Spain", "region": "Madrid", "continent": "Europe"},
  {"placeName": "Longyearbyen", "country": "Svalbard and Jan Mayen", "region": "Svalbard", "continent": "Europe"},
  {"placeName": "Stockholm", "country": "Sweden", "region": "Stockholm", "continent": "Europe"},
  {"placeName": "Zürich", "country": "Switzerland", "region": "Zurich", "continent": "Europe"},
  {"placeName": "Rotterdam", "country": "The Netherlands", "region": "South Holland", "continent": "Europe"},
  {"placeName": "Kyiv", "country": "Ukraine", "region": "Kyiv City", "continent": "Europe"},
  {"placeName": "London", "country": "United Kingdom", "region": "England", "continent": "Europe"},
  {"placeName": "Vatican City", "country": "Vatican", "region": null, "continent": "Europe"},
  {"placeName": "The Valley", "country": "Anguilla", "region": "The Valley", "continent": "North America"},
  {"placeName": "Saint John’s", "country": "Antigua and Barbuda", "region": "Saint John Parish", "continent": "North America"},
  {"placeName": "Oranjestad", "country": "Aruba", "region": null, "continent": "North America"},
  {"placeName": "Nassau", "country": "Bahamas", "region": "New Providence", "continent": "North America"},
  {"placeName": "Bridgetown", "country": "Barbados", "region": "Saint Michael", "continent": "North America"},
  {"placeName": "Belize City", "country": "Belize", "region": "Belize District", "continent": "North America"},
  {"placeName": "Pembroke Parish", "country": "Bermuda", "region": "Pembroke", "continent": "North America"},
  {"placeName": "Kralendijk", "country": "Bonaire, Saint Eustatius and Saba", "region": "Bonaire", "continent": "North America"},
  {"placeName": "Road Town", "country": "British Virgin Islands", "region": null, "continent": "North America"},
  {"placeName": "Calgary", "country": "Canada", "region": "Alberta", "continent": "North America"},
  {"placeName": "Montréal", "country": "Canada", "region": "Quebec", "continent": "North America"},
  {"placeName": "Toronto", "country": "Canada", "region": "Ontario", "continent": "North America"},
  {"placeName": "George Town", "country": "Cayman Islands", "region": "George Town", "continent": "North America"},
  {"placeName": "San José", "country": "Costa Rica", "region": "San José", "continent": "North America"},
  {"placeName": "Havana", "country": "Cuba", "region": "Havana", "continent": "North America"},
  {"placeName": "Willemstad", "country": "Curacao", "region": null, "continent": "North America"},
  {"placeName": "Roseau", "country": "Dominica", "region": "Saint George Parish", "continent": "North America"},
  {"placeName": "Santiago de los Caballeros", "country": "Dominican Republic", "region": "Santiago Province", "continent": "North America"},
  {"placeName": "Santo Domingo", "country": "Dominican Republic", "region": "Nacional", "continent": "North America"},
  {"placeName": "Santo Domingo Oeste", "country": "Dominican Republic", "region": "Santo Domingo Province", "continent": "North America"},
  {"placeName": "San Salvador", "country": "El Salvador", "region": "San Salvador Department", "continent": "North America"},
  {"placeName": "Nuuk", "country": "Greenland", "region": "Sermersooq", "continent": "North America"},
  {"placeName": "Saint George's", "country": "Grenada", "region": "Saint George Parish", "continent": "North America"},
  {"placeName": "Les Abymes", "country": "Guadeloupe", "region": "Guadeloupe", "continent": "North America"},
  {"placeName": "Guatemala City", "country": "Guatemala", "region": "Guatemala", "continent": "North America"},
  {"placeName": "Port-au-Prince", "country": "Haiti", "region": "Ouest", "continent": "North America"},
  {"placeName": "San Pedro Sula", "country": "Honduras", "region": "Cortés Department", "continent": "North America"},
  {"placeName": "Tegucigalpa", "country": "Honduras", "region": "Francisco Morazán Department", "continent": "North America"},
  {"placeName": "Kingston", "country": "Jamaica", "region": "Kingston", "continent": "North America"},
  {"placeName": "Fort-de-France", "country": "Martinique", "region": "Martinique", "continent": "North America"},
  {"placeName": "Iztapalapa", "country": "Mexico", "region": "Mexico City", "continent": "North America"},
  {"placeName": "Mexico City", "country": "Mexico", "region": "Mexico City", "continent": "North America"},
  {"placeName": "Tijuana", "country": "Mexico", "region": "Baja California", "continent": "North America"},
  {"placeName": "Brades", "country": "Montserrat", "region": "Saint Peter", "continent": "North America"},
  {"placeName": "Managua", "country": "Nicaragua", "region": "Managua Department", "continent": "North America"},
  {"placeName": "Panama City", "country": "Panama", "region": "Panamá", "continent": "North America"},
  {"placeName": "San Juan", "country": "Puerto Rico", "region": "San Juan", "continent": "North America"},
  {"placeName": "Gustavia", "country": "Saint Barthelemy", "region": null, "continent": "North America"},
  {"placeName": "Basseterre", "country": "Saint Kitts and Nevis", "region": "Saint George Basseterre", "continent": "North America"},
  {"placeName": "Gros Islet", "country": "Saint Lucia", "region": "Gros-Islet", "continent": "North America"},
  {"placeName": "Grand-Case", "country": "Saint Martin", "region": null, "continent": "North America"},
  {"placeName": "Saint-Pierre", "country": "Saint Pierre and Miquelon", "region": "Saint-Pierre", "continent": "North America"},
  {"placeName": "Kingstown", "country": "Saint Vincent and the Grenadines", "region": "Saint George Parish", "continent": "North America"},
  {"placeName": "Cul de Sac", "country": "Sint Maarten", "region": null, "continent": "North America"},
  {"placeName": "Chaguanas", "country": "Trinidad and Tobago", "region": "Chaguanas", "continent": "North America"},
  {"placeName": "Providenciales", "country": "Turks and Caicos Islands", "region": null, "continent": "North America"},
  {"placeName": "Saint Croix", "country": "U.S. Virgin Islands", "region": "Saint Croix Island", "continent": "North America"},
  {"placeName": "Brooklyn", "country": "United States", "region": "New York", "continent": "North America"},
  {"placeName": "Los Angeles", "country": "United States", "region": "California", "continent": "North America"},
  {"placeName": "New York City", "country": "United States", "region": "New York", "continent": "North America"},
  {"placeName": "Pago Pago", "country": "American Samoa", "region": "Eastern District", "continent": "Oceania"},
  {"placeName": "Brisbane", "country": "Australia", "region": "Queensland", "continent": "Oceania"},
  {"placeName": "Melbourne", "country": "Australia", "region": "Victoria", "continent": "Oceania"},
  {"placeName": "Sydney", "country": "Australia", "region": "New South Wales", "continent": "Oceania"},
  {"placeName": "Flying Fish Cove", "country": "Christmas Island", "region": null, "continent": "Oceania"},
  {"placeName": "Avarua", "country": "Cook Islands", "region": "Rarotonga", "continent": "Oceania"},
  {"placeName": "Lautoka", "country": "Fiji", "region": "Western", "continent": "Oceania"},
  {"placeName": "Nasinu", "country": "Fiji", "region": "Central", "continent": "Oceania"},
  {"placeName": "Suva", "country": "Fiji", "region": "Central", "continent": "Oceania"},
  {"placeName": "Faaa", "country": "French Polynesia", "region": "Îles du Vent", "continent": "Oceania"},
  {"placeName": "Papeete", "country": "French Polynesia", "region": "Îles du Vent", "continent": "Oceania"},
  {"placeName": "Punaauia", "country": "French Polynesia", "region": "Îles du Vent", "continent": "Oceania"},
  {"placeName": "Dededo Village", "country": "Guam", "region": "Dededo", "continent": "Oceania"},
  {"placeName": "Tamuning", "country": "Guam", "region": "Tamuning", "continent": "Oceania"},
  {"placeName": "Yigo Village", "country": "Guam", "region": "Yigo", "continent": "Oceania"},
  {"placeName": "Tarawa", "country": "Kiribati", "region": "Gilbert Islands", "continent": "Oceania"},
  {"placeName": "Dalap-Uliga-Dorrit", "country": "Marshall Islands", "region": "Majuro Atoll", "continent": "Oceania"},
  {"placeName": "Ebaye", "country": "Marshall Islands", "region": "Kwajalein Atoll", "continent": "Oceania"},
  {"placeName": "Majuro", "country": "Marshall Islands", "region": "Majuro Atoll", "continent": "Oceania"},
  {"placeName": "Weno", "country": "Micronesia", "region": "Chuuk", "continent": "Oceania"},
  {"placeName": "Yangor", "country": "Nauru", "region": "Aiwo District", "continent": "Oceania"},
  {"placeName": "Dumbéa", "country": "New Caledonia", "region": "South Province", "continent": "Oceania"},
  {"placeName": "Mont-Dore", "country": "New Caledonia", "region": "South Province", "continent": "Oceania"},
  {"placeName": "Nouméa", "country": "New Caledonia", "region": "South Province", "continent": "Oceania"},
  {"placeName": "Auckland", "country": "New Zealand", "region": "Auckland", "continent": "Oceania"},
  {"placeName": "Christchurch", "country": "New Zealand", "region": "Canterbury", "continent": "Oceania"},
  {"placeName": "Wellington", "country": "New Zealand", "region": "Wellington Region", "continent": "Oceania"},
  {"placeName": "Alofi", "country": "Niue", "region": null, "continent": "Oceania"},
  {"placeName": "Kingston", "country": "Norfolk Island", "region": null, "continent": "Oceania"},
  {"placeName": "Saipan", "country": "Northern Mariana Islands", "region": "Saipan", "continent": "Oceania"},
  {"placeName": "San Jose Village", "country": "Northern Mariana Islands", "region": "Tinian", "continent": "Oceania"},
  {"placeName": "Koror", "country": "Palau", "region": "Koror", "continent": "Oceania"},
  {"placeName": "Arawa", "country": "Papua New Guinea", "region": "Bougainville", "continent": "Oceania"},
  {"placeName": "Lae", "country": "Papua New Guinea", "region": "Morobe Province", "continent": "Oceania"},
  {"placeName": "Port Moresby", "country": "Papua New Guinea", "region": "National Capital", "continent": "Oceania"},
  {"placeName": "Adamstown", "country": "Pitcairn", "region": null, "continent": "Oceania"},
  {"placeName": "Apia", "country": "Samoa", "region": "Tuamasaga", "continent": "Oceania"},
  {"placeName": "Honiara", "country": "Solomon Islands", "region": "Honiara", "continent": "Oceania"},
  {"placeName": "Nggosi", "country": "Solomon Islands", "region": "Guadalcanal Province", "continent": "Oceania"},
  {"placeName": "Panatina", "country": "Solomon Islands", "region": "Honiara", "continent": "Oceania"},
  {"placeName": "Dili", "country": "Timor Leste", "region": "Dili Municipality", "continent": "Oceania"},
  {"placeName": "Maliana", "country": "Timor Leste", "region": "Bobonaro", "continent": "Oceania"},
  {"placeName": "Suai", "country": "Timor Leste", "region": "Cova Lima", "continent": "Oceania"},
  {"placeName": "Nukunonu", "country": "Tokelau", "region": "Nukunonu", "continent": "Oceania"},
  {"placeName": "Nuku‘alofa", "country": "Tonga", "region": "Tongatapu", "continent": "Oceania"},
  {"placeName": "Funafuti", "country": "Tuvalu", "region": "Funafuti", "continent": "Oceania"},
  {"placeName": "Luganville", "country": "Vanuatu", "region": "Sanma", "continent": "Oceania"},
  {"placeName": "Port-Vila", "country": "Vanuatu", "region": "Shefa", "continent": "Oceania"},
  {"placeName": "Mata-Utu", "country": "Wallis and Futuna", "region": "Uvea", "continent": "Oceania"},
  {"placeName": "Buenos Aires", "country": "Argentina", "region": "Buenos Aires F.D.", "continent": "South America"},
  {"placeName": "Córdoba", "country": "Argentina", "region": "Cordoba", "continent": "South America"},
  {"placeName": "Rosario", "country": "Argentina", "region": "Santa Fe", "continent": "South America"},
  {"placeName": "Cochabamba", "country": "Bolivia", "region": "Cochabamba", "continent": "South America"},
  {"placeName": "La Paz", "country": "Bolivia", "region": "La Paz Department", "continent": "South America"},
  {"placeName": "Santa Cruz de la Sierra", "country": "Bolivia", "region": "Santa Cruz Department", "continent": "South America"},
  {"placeName": "Belo Horizonte", "country": "Brazil", "region": "Minas Gerais", "continent": "South America"},
  {"placeName": "Rio de Janeiro", "country": "Brazil", "region": "Rio de Janeiro", "continent": "South America"},
  {"placeName": "São Paulo", "country": "Brazil", "region": "São Paulo", "continent": "South America"},
  {"placeName": "Maipú", "country": "Chile", "region": "Santiago Metropolitan", "continent": "South America"},
  {"placeName": "Puente Alto", "country": "Chile", "region": "Santiago Metropolitan", "continent": "South America"},
  {"placeName": "Santiago", "country": "Chile", "region": "Santiago Metropolitan", "continent": "South America"},
  {"placeName": "Bogotá", "country": "Colombia", "region": "Bogota D.C.", "continent": "South America"},
  {"placeName": "Cali", "country": "Colombia", "region": "Valle del Cauca Department", "continent": "South America"},
  {"placeName": "Medellín", "country": "Colombia", "region": "Antioquia", "continent": "South America"},
  {"placeName": "Cuenca", "country": "Ecuador", "region": "Azuay", "continent": "South America"},
  {"placeName": "Guayaquil", "country": "Ecuador", "region": "Guayas", "continent": "South America"},
  {"placeName": "Quito", "country": "Ecuador", "region": "Pichincha", "continent": "South America"},
  {"placeName": "Stanley", "country": "Falkland Islands", "region": null, "continent": "South America"},
  {"placeName": "Cayenne", "country": "French Guiana", "region": "Guyane", "continent": "South America"},
  {"placeName": "Matoury", "country": "French Guiana", "region": "Guyane", "continent": "South America"},
  {"placeName": "Saint-Laurent-du-Maroni", "country": "French Guiana", "region": "Guyane", "continent": "South America"},
  {"placeName": "Georgetown", "country": "Guyana", "region": "Demerara-Mahaica", "continent": "South America"},
  {"placeName": "Linden", "country": "Guyana", "region": "Upper Demerara-Berbice", "continent": "South America"},
  {"placeName": "New Amsterdam", "country": "Guyana", "region": "East Berbice-Corentyne", "continent": "South America"},
  {"placeName": "Asunción", "country": "Paraguay", "region": "Asuncion", "continent": "South America"},
  {"placeName": "Ciudad del Este", "country": "Paraguay", "region": "Alto Paraná Department", "continent": "South America"},
  {"placeName": "San Lorenzo", "country": "Paraguay", "region": "Central Department", "continent": "South America"},
  {"placeName": "Arequipa", "country": "Peru", "region": "Arequipa", "continent": "South America"},
  {"placeName": "Callao", "country": "Peru", "region": "Callao", "continent": "South America"},
  {"placeName": "Lima", "country": "Peru", "region": "Lima Province", "continent": "South America"},
  {"placeName": "Blauwgrond", "country": "Suriname", "region": "Paramaribo District", "continent": "South America"},
  {"placeName": "Latour", "country": "Suriname", "region": "Paramaribo District", "continent": "South America"},
  {"placeName": "Paramaribo", "country": "Suriname", "region": "Paramaribo District", "continent": "South America"},
  {"placeName": "Maldonado", "country": "Uruguay", "region": "Maldonado", "continent": "South America"},
  {"placeName": "Montevideo", "country": "Uruguay", "region": "Montevideo Department", "continent": "South America"},
  {"placeName": "Salto", "country": "Uruguay", "region": "Salto Department", "continent": "South America"},
  {"placeName": "Caracas", "country": "Venezuela", "region": "Distrito Federal", "continent": "South America"},
  {"placeName": "Maracaibo", "country": "Venezuela", "region": "Zulia", "continent": "South America"},
  {"placeName": "Valencia", "country": "Venezuela", "region": "Carabobo", "continent": "South America"},
];
