const normalizeLocale = (locale: string): string => locale.trim().toLowerCase().split('-')[0];

const translations = {
  en: {
    meta: {
      title: 'Silicon Traveler - Walking Around the World',
      description: "A virtual photographer's journey around the world on foot, generated by AI",
    },
    nav: {
      journal: 'Journal',
      archive: 'Archive',
      map: 'Map',
    },
    photo: {
      technicalPlate: 'Technical Plate',
      location: 'Location',
      expandArchive: 'Expand Archive',
      prevPhoto: 'Previous photo',
      nextPhoto: 'Next photo',
      volume: 'Volume',
      allRights: 'All Rights Reserved',
    },
    home: {
      noPhotosTitle: 'No photos published yet.',
      noPhotosBody: 'The journal will open with the first published frame. Check back soon.',
      viewArchive: 'View Archive',
    },
    archive: {
      title: 'Archive',
      searchPlaceholder: 'SEARCH BY LOCATION, TITLE, NARRATIVE, OR TAG',
      dateRange: 'Date Range',
      dateRangeLabel: 'Date range filter',
      filterByPublished: 'Filter by published date',
      closeDateRange: 'Close date range panel',
      startDate: 'Start date',
      endDate: 'End date',
      apply: 'Apply',
      clear: 'Clear',
      geography: 'Geography',
      noResults: 'No results. Refine your search.',
      noPhotos: 'No photos published yet.',
      viewAll: 'View all photos',
      returnJournal: 'Return to Journal',
      seriesFallback: 'Silicon Traveler Journal',
      sheetLabel: (month: string, year: number) => `Sheet ${month} / ${year}`,
      rollLabel: 'ROLL',
      unknownLocation: 'Unknown location',
      prev: 'Prev',
      next: 'Next',
      paginationSummary: (
        start: number | string,
        end: number | string,
        count: number | string,
        current: number | string,
        total: number | string
      ) => `Visualizing ${start}-${end} of ${count} frames | Page ${current} of ${total}`,
      footerTitle: 'The Silicon Traveler Archive',
      footerBody:
        'A daily exercise in observation. One photograph, one reflection, every 24 hours. A lifetime of seeing, cataloged and preserved for the public record.',
      footerStats: (photos: number | string, distanceKm: number | string) =>
        `${photos} frames | ${distanceKm}km traveled`,
      footerFallback: 'Documenting the journey',
    },
    map: {
      title: 'Map',
      viewport: 'Viewport',
      updating: 'Updating...',
      filterPlaceholder: 'Filter by location, title, narrative, tags',
      mapState: 'Map State',
      zoom: 'Zoom',
      center: 'Center',
      updated: 'Updated',
      selectedFrame: 'Selected Frame',
      selectPin: 'Select a pin to reveal the photo metadata.',
      pinCount: (count: number | string) => `${count} pins`,
    },
    stats: {
      line: (photos: number | string, distanceKm: number | string, locations: number | string) =>
        `${photos} photos | ${distanceKm}km traveled | ${locations} locations`,
    },
    admin: {
      title: 'Admin',
      empty: 'No route points found.',
      filters: {
        status: 'Status',
      },
      status: {
        all: 'All',
        pending: 'Pending',
        researched: 'Researched',
        content_generated: 'Content generated',
        image_ready: 'Image ready',
        published: 'Published',
        failed: 'Failed',
      },
      table: {
        sequence: 'Seq',
        status: 'Status',
        city: 'City',
        country: 'Country',
        updated: 'Updated',
        actions: 'Actions',
      },
      fields: {
        city: 'City',
        country: 'Country',
        region: 'Region',
        status: 'Status',
        lat: 'Lat',
        lng: 'Lng',
        prompt: 'Prompt',
        text: 'Text',
        photo: 'Photo',
      },
      publishSwitch: {
        label: 'Published',
        help: 'Toggle visibility in public archive and map.',
        checkedLabel: 'Visible',
        uncheckedLabel: 'Hidden',
      },
      placeholders: {
        city: 'e.g. Tokyo',
        country: 'e.g. Japan',
        region: 'e.g. Kanto',
        prompt: 'Image prompt...',
        text: 'Narrative / text...',
      },
      actions: {
        apply: 'Apply',
        edit: 'Edit',
        save: 'Save',
        delete: 'Delete',
        back: 'Back',
        logout: 'Logout',
        cancel: 'Cancel',
        create: 'Create',
        addRoutePoint: 'Add Route Point',
        uploadJpeg: 'Upload JPEG',
      },
      geocode: {
        calculate: 'Calculate coordinates',
        calculating: 'Calculating...',
        success: 'Coordinates updated.',
        errors: {
          cityRequired: 'Enter a city first.',
          notFound: 'Location not found.',
          failed: 'Could not calculate coordinates.',
        },
      },
      new: {
        title: 'New Route Point',
      },
      edit: {
        title: 'Edit Route Point',
      },
      login: {
        title: 'Admin Login',
        description: 'Restricted area. Sign in to manage route points.',
        fields: {
          username: 'Username',
          password: 'Password',
        },
        actions: {
          signIn: 'Sign in',
        },
        errors: {
          invalidCredentials: 'Invalid credentials.',
        },
      },
      deleteModal: {
        title: 'Delete route point?',
        description: 'This action cannot be undone.',
        confirm: 'Delete permanently',
        cancel: 'Cancel',
      },
      fallback: {
        unknown: 'Unknown',
        noPhoto: 'No photo',
      },
      alt: {
        routePointPhoto: 'Route point photo',
      },
      success: {
        saved: 'Changes saved.',
        deleted: 'Route point deleted.',
      },
      errors: {
        invalidCoordinates: 'Invalid coordinates.',
        saveFailed: 'Could not save changes.',
        publishNotReady: 'Route point must be image-ready before publishing.',
        publishMissingImage: 'Upload a route-point image before publishing.',
        deleteFailed: 'Could not delete route point.',
        photoRequired: 'Please select a JPEG file.',
        photoType: 'Only JPEG is supported right now.',
        photoFailed: 'Could not upload the photo.',
        unknown: 'Something went wrong.',
      },
    },
  },
  es: {
    meta: {
      title: 'Silicon Traveler - Caminando alrededor del mundo',
      description: 'El viaje de un fotógrafo virtual alrededor del mundo a pie, generado por IA',
    },
    nav: {
      journal: 'Diario',
      archive: 'Archivo',
      map: 'Mapa',
    },
    photo: {
      technicalPlate: 'Ficha técnica',
      location: 'Ubicación',
      expandArchive: 'Explorar archivo',
      prevPhoto: 'Foto anterior',
      nextPhoto: 'Siguiente foto',
      volume: 'Volumen',
      allRights: 'Todos los derechos reservados',
    },
    home: {
      noPhotosTitle: 'Aún no hay fotos publicadas.',
      noPhotosBody: 'El diario se abrirá con el primer fotograma publicado. Vuelve pronto.',
      viewArchive: 'Ver archivo',
    },
    archive: {
      title: 'Archivo',
      searchPlaceholder: 'BUSCAR POR UBICACIÓN, TÍTULO, NARRATIVA O ETIQUETA',
      dateRange: 'Rango de fechas',
      dateRangeLabel: 'Filtro de rango de fechas',
      filterByPublished: 'Filtrar por fecha de publicación',
      closeDateRange: 'Cerrar selector de fechas',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de fin',
      apply: 'Aplicar',
      clear: 'Limpiar',
      geography: 'Geografía',
      noResults: 'Sin resultados. Ajusta tu búsqueda.',
      noPhotos: 'Aún no hay fotos publicadas.',
      viewAll: 'Ver todas las fotos',
      returnJournal: 'Volver al diario',
      seriesFallback: 'Diario de Silicon Traveler',
      sheetLabel: (month: string, year: number) => `Hoja ${month} / ${year}`,
      rollLabel: 'ROLLO',
      unknownLocation: 'Ubicación desconocida',
      prev: 'Anterior',
      next: 'Siguiente',
      paginationSummary: (
        start: number | string,
        end: number | string,
        count: number | string,
        current: number | string,
        total: number | string
      ) => `Mostrando ${start}-${end} de ${count} fotogramas | Página ${current} de ${total}`,
      footerTitle: 'El Archivo de Silicon Traveler',
      footerBody:
        'Un ejercicio diario de observación. Una fotografía, una reflexión, cada 24 horas. Una vida de miradas, catalogada y preservada para el registro público.',
      footerStats: (photos: number | string, distanceKm: number | string) =>
        `${photos} fotogramas | ${distanceKm}km recorridos`,
      footerFallback: 'Documentando el viaje',
    },
    map: {
      title: 'Mapa',
      viewport: 'Vista',
      updating: 'Actualizando...',
      filterPlaceholder: 'Filtrar por ubicación, título, narrativa o etiquetas',
      mapState: 'Estado del mapa',
      zoom: 'Zoom',
      center: 'Centro',
      updated: 'Actualizado',
      selectedFrame: 'Fotograma seleccionado',
      selectPin: 'Selecciona un pin para ver los metadatos de la foto.',
      pinCount: (count: number | string) => `${count} marcadores`,
    },
    stats: {
      line: (photos: number | string, distanceKm: number | string, locations: number | string) =>
        `${photos} fotos | ${distanceKm}km recorridos | ${locations} lugares`,
    },
    admin: {
      title: 'Admin',
      empty: 'No se encontraron puntos de ruta.',
      filters: {
        status: 'Estado',
      },
      status: {
        all: 'Todos',
        pending: 'Pendiente',
        researched: 'Investigado',
        content_generated: 'Contenido generado',
        image_ready: 'Imagen lista',
        published: 'Publicado',
        failed: 'Fallido',
      },
      table: {
        sequence: 'Sec',
        status: 'Estado',
        city: 'Ciudad',
        country: 'Pais',
        updated: 'Actualizado',
        actions: 'Acciones',
      },
      fields: {
        city: 'Ciudad',
        country: 'Pais',
        region: 'Region',
        status: 'Estado',
        lat: 'Lat',
        lng: 'Lng',
        prompt: 'Prompt',
        text: 'Texto',
        photo: 'Foto',
      },
      publishSwitch: {
        label: 'Publicado',
        help: 'Activa o desactiva su visibilidad en archivo y mapa.',
        checkedLabel: 'Visible',
        uncheckedLabel: 'Oculto',
      },
      placeholders: {
        city: 'p.ej. Tokyo',
        country: 'p.ej. Japon',
        region: 'p.ej. Kanto',
        prompt: 'Prompt de imagen...',
        text: 'Narrativa / texto...',
      },
      actions: {
        apply: 'Aplicar',
        edit: 'Editar',
        save: 'Guardar',
        delete: 'Borrar',
        back: 'Volver',
        logout: 'Salir',
        cancel: 'Cancelar',
        create: 'Crear',
        addRoutePoint: 'Nuevo punto',
        uploadJpeg: 'Subir JPEG',
      },
      geocode: {
        calculate: 'Calcular coordenadas',
        calculating: 'Calculando...',
        success: 'Coordenadas actualizadas.',
        errors: {
          cityRequired: 'Primero indica una ciudad.',
          notFound: 'No se encontro la ubicacion.',
          failed: 'No se pudieron calcular las coordenadas.',
        },
      },
      new: {
        title: 'Nuevo punto de ruta',
      },
      edit: {
        title: 'Editar punto de ruta',
      },
      login: {
        title: 'Acceso Admin',
        description: 'Area restringida. Inicia sesion para gestionar puntos de ruta.',
        fields: {
          username: 'Usuario',
          password: 'Contrasena',
        },
        actions: {
          signIn: 'Entrar',
        },
        errors: {
          invalidCredentials: 'Credenciales invalidas.',
        },
      },
      deleteModal: {
        title: 'Borrar punto de ruta?',
        description: 'Esta accion no se puede deshacer.',
        confirm: 'Borrar definitivamente',
        cancel: 'Cancelar',
      },
      fallback: {
        unknown: 'Desconocido',
        noPhoto: 'Sin foto',
      },
      alt: {
        routePointPhoto: 'Foto del punto de ruta',
      },
      success: {
        saved: 'Cambios guardados.',
        deleted: 'Punto de ruta borrado.',
      },
      errors: {
        invalidCoordinates: 'Coordenadas invalidas.',
        saveFailed: 'No se pudieron guardar los cambios.',
        publishNotReady: 'El punto debe estar en estado imagen lista para publicarse.',
        publishMissingImage: 'Sube una imagen del punto antes de publicarlo.',
        deleteFailed: 'No se pudo borrar el punto de ruta.',
        photoRequired: 'Selecciona un archivo JPEG.',
        photoType: 'Por ahora solo se admite JPEG.',
        photoFailed: 'No se pudo subir la foto.',
        unknown: 'Algo fallo.',
      },
    },
  },
} as const;

export type Translations = (typeof translations)[keyof typeof translations];

export function getTranslations(locale: string, fallbackLocale: string = 'es'): Translations {
  const normalized = normalizeLocale(locale || fallbackLocale);
  const fallback = normalizeLocale(fallbackLocale);
  return (
    translations[normalized as keyof typeof translations] ||
    translations[fallback as keyof typeof translations] ||
    translations.es
  );
}

export function getLocaleKey(locale: string, fallbackLocale: string = 'es'): string {
  const normalized = normalizeLocale(locale || fallbackLocale);
  if (translations[normalized as keyof typeof translations]) {
    return normalized;
  }
  return normalizeLocale(fallbackLocale);
}
